# Assignment 1  
46110 Basic Aerodynamics

In [3]:
# Modules
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt
%matplotlib inline

### A)
Determine $\dfrac{m_1}{c}$ and $\dfrac{m_2}{c}$ for the Joukowski airfoil with relative (to chord) thicknesses of 10%, 20% and 30% and maximum camber 0% and 10%.  
Also try to do this with the linearized approach from the book.

Numerical approach:  
Transformation: $z = \zeta+\dfrac{c^2}{\zeta}$  


In [4]:
# Parameters
alphad = 0 # angle of attack (for D and E)
m1oc = 0. # m1/c 
m2oc = 0. # m2/c
R = 1. # Radius of transformation circle

theta_str = str(alphad)+'°'
alpha = alphad*np.pi/180
c = R/np.sqrt(m2oc**2+(1+m1oc)**2)
c2 = c**2
chord = 4*c
m1 = m1oc*c
m2 = m2oc*c
s = -m1 + 1j*m2

# Targets
toc = np.array([0.1, 0.2, 0.3]) # max relative thickness
hoc = np.array([0, 0.1]) # max relative camber

Max thickness: $\dfrac{t}{c}\bigg) _{max}$  
Max camber: $\dfrac{h}{c}\bigg) _{max}$  
Just take thickness as be the difference in y-values so $t=y_u-y_l$  
With the camber line: $h = \dfrac{y_y+y_l}{2}$

In [28]:
N = 2000 # EVEN number
x_start, x_end = -5.0, 5.0        # boundaries for x-dir.
y_start, y_end = -5.0, 5.0        # boundaries for y-dir.
x_ar = np.linspace(x_start, x_end, N)    #
y_ar = np.linspace(y_start, y_end, N)
x, y = np.meshgrid(x_ar,y_ar)               # meshes grid

# Complex mesh plane
z = x+1j*y

# Exclusion of points inside circle
for i in range(N):
    for j in range(N):
        if abs(z[i,j])<= (R-5e-3):
            z[i,j] = complex(float('nan'),float('nan'))
#z = z[None,:,:]

In [27]:
M1 = 400
M2 = 400
n_tests = int(M1*M2) # Number of tests

# Various values for m1/c and m2/c
m1oc = np.linspace(0, 0.4, M1) 
m2oc = np.linspace(0, 0.4, M2)

## Testing the different values

# Empty array to fill in
r_t = np.array([]) # max relative thickness
r_c = np.array([]) # max relative camber
r_m1oc = np.array([]) # m1oc value
r_m2oc = np.array([]) # m2oc value

# Actual testing
for i in range(M1):
    for j in range(M2):
        c = R/np.sqrt(m2oc[j]**2+(1+m1oc[i])**2)
        c2 = c**2
        chord = 4*c
        m1 = m1oc[i]*c
        m2 = m2oc[j]*c
        s = -m1 + 1j*m2 # center of circle in zeta
        J = z+c2/z # Joukowski transformation of all points

        angle = np.linspace(0, 2*np.pi, N) 
        
        # coord. for circle periphery
        z_circle = R*(np.cos(angle)+1j*np.sin(angle)) + s
        
        # coord. for airfoil periphery (J-transform of circle)
        z_airfoil = z_circle+c2/z_circle
        
        
        # Upper part of airfoil (from right to left)
        leftMostPoint = np.argmin(z_airfoil.real)
        za_upper = z_airfoil[:(leftMostPoint-1)]
        za_upper = za_upper[::-1] # Reversing array order
        
        # Lower part of airfoil (left to right)
        za_lower = z_airfoil[(int(leftMostPoint)+1):]

        # Interpolation functions for upper and lower airfoil curve
        fu = interpolate.interp1d(za_upper.real,za_upper.imag, kind='cubic',bounds_error=False)
        fl = interpolate.interp1d(za_lower.real,za_lower.imag, kind='cubic',bounds_error=False)
        
        # Limit values for interpolation.
        # Edge values are removed to avoid any errors
        lim1 = np.min( z_airfoil.real )*0.95
        lim2 = np.max( z_airfoil.real )*0.95
        # Evaluation points
        span1 = np.linspace(lim1,lim2,200)
        
        
        # Finding max relative thickness
        max_t = np.max( (fu(span) - fl(span))/chord )
        max_camber = np.max( (fu(span)+fl(span))/2 )
        
        # Save result
        r_t = np.append(r_t, max_t)
        r_c = np.append(r_c, max_camber)
        r_m1oc = np.append(r_m1oc, m1oc[i])
        r_m2oc = np.append(r_m2oc, m2oc[j])

In [ ]:
np.savetxt('maxRelThickness.txt',r_t)
np.savetxt('maxRelCamber.txt',r_c)
np.savetxt('m1oc.txt',r_m1oc)
np.savetxt('m2oc.txt',r_m2oc)

In [25]:
za_lower.real

array([-1.97272261, -1.7589475 , -1.35456314, -0.80339085, -0.16515869,
        0.49097097,  1.09389632,  1.57828102,  1.89163448,  2.        ])

In [ ]:
a = np.array([])

In [ ]:
a = np.append(a,3)

In [18]:
tt=np.linspace(-0.5,0.5,100)

In [19]:
fu(tt)

array([  2.83878153e-17,   2.85266816e-17,   2.86085428e-17,
         2.86329261e-17,   2.85993591e-17,   2.85073689e-17,
         2.83564828e-17,   2.81462283e-17,   2.78761326e-17,
         2.75457230e-17,   2.71545269e-17,   2.67020717e-17,
         2.61878845e-17,   2.56114927e-17,   2.49724237e-17,
         2.42702048e-17,   2.35043633e-17,   2.26744265e-17,
         2.17799218e-17,   2.08203764e-17,   1.97953177e-17,
         1.87042730e-17,   1.75467697e-17,   1.63223350e-17,
         1.50304963e-17,   1.36707808e-17,   1.22427160e-17,
         1.07458291e-17,   9.17964749e-18,   7.54369845e-18,
         5.83750931e-18,   4.06060740e-18,   2.21252003e-18,
         2.92774526e-19,  -1.69867357e-18,  -3.75917266e-18,
        -5.88502454e-18,  -8.07252869e-18,  -1.03179846e-17,
        -1.26176917e-17,  -1.49679496e-17,  -1.73650576e-17,
        -1.98053154e-17,  -2.22850223e-17,  -2.48004778e-17,
        -2.73479815e-17,  -2.99238328e-17,  -3.25243311e-17,
        -3.51457761e-17,

In [11]:
span

array([-1.87408648, -1.85512122, -1.83615596, -1.8171907 , -1.79822544,
       -1.77926018, -1.76029492, -1.74132967, -1.72236441, -1.70339915,
       -1.68443389, -1.66546863, -1.64650337, -1.62753811, -1.60857286,
       -1.5896076 , -1.57064234, -1.55167708, -1.53271182, -1.51374656,
       -1.4947813 , -1.47581604, -1.45685079, -1.43788553, -1.41892027,
       -1.39995501, -1.38098975, -1.36202449, -1.34305923, -1.32409397,
       -1.30512872, -1.28616346, -1.2671982 , -1.24823294, -1.22926768,
       -1.21030242, -1.19133716, -1.17237191, -1.15340665, -1.13444139,
       -1.11547613, -1.09651087, -1.07754561, -1.05858035, -1.03961509,
       -1.02064984, -1.00168458, -0.98271932, -0.96375406, -0.9447888 ,
       -0.92582354, -0.90685828, -0.88789303, -0.86892777, -0.84996251,
       -0.83099725, -0.81203199, -0.79306673, -0.77410147, -0.75513621,
       -0.73617096, -0.7172057 , -0.69824044, -0.67927518, -0.66030992,
       -0.64134466, -0.6223794 , -0.60341415, -0.58444889, -0.56

In [10]:
np.max( z_airfoil.real )

2.0

### A) Results

$t_{rel, max}$: 0.10005 - $m/c$= (0.081, 0.200)  
$t_{rel, max}$: 0.09993 - $m/c$= (0.083, 0.044)  
$t_{rel, max}$: 0.10009 - $m/c$= (0.083, 0.067)  
  


In [ ]:
a = np.array([])

In [ ]:
a = np.append(np.array([1,2,3]),a,axis=1)

In [ ]:
a

In [ ]:
plt.plot(za_upper.real,za_upper.imag,'ro')
plt.plot(za_lower.real,za_lower.imag,'bo')

In [ ]:
plt.plot(z_circle.real, z_circle.imag)

In [ ]:
plt.plot(za_upper.real-za_lower.real)

In [ ]:
plt.plot(z_airfoil.real, z_airfoil.imag,'o')

In [ ]:
        if 0.0990< max_trel < 0.1010:
            # Print and plot if within tolerance.
            ind = np.argmax((fu(span) - fl(span))/chord) # index in span
            print('trel: {0:.5f} - m/c= ({1:.3f}, {2:.3f})'.format(max_trel, m1oc[i], m2oc[j]))
            plt.plot(span,fu(span),'.-b')
            plt.plot(span,fl(span),'.-r')
            plt.plot(span[ind],fu(span[ind]),'ro',ms=5)
            plt.plot(span[ind],fl(span[ind]),'bo',ms=5)